# Generated by Django 3.2 on 2021-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.IntegerField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=100)),
                ('sID', models.IntegerField()),
            ],
            options={
                'db_table': 'City',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cID', models.IntegerField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('sID', models.IntegerField(primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=100)),
                ('cID', models.IntegerField()),
            ],
            options={
                'db_table': 'State',
                'managed': True,
            },
        ),
    ]
